name: kanye breath
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading ngrok
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/nathannxx/onesixtwo612/main/ngrok.exe -OutFile ngrok.exe
          
